### ISSUE TITLE
Does not work on windows because of Mono.Posix dependency

### ISSUE THREAD

**Issue by BitPuffin** [mono/sdb#30]
Hey I'm trying to use sdb on windows but it started screaming about that it couldn't load assembly Mono.Posix. So I tried installing gtksharp and copied its Mono.Posix.dll to the directory with sdb.exe. However this didn't work either and is now screaming at me like this:

```

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Mono.Debugger.Client.Program.Main(String[] args)

```

**Comment by alexrp** [comment]
Are you running `sdb` under Mono or .NET?

**Comment by cubrr** [comment]
Can confirm that this happens when running under .NET. No problems running under mono.
```mono sdb.exe```

**Comment by alexrp** [comment]
I guess the runtime is trying to load `Mono.Posix.dll` because of the call to `Stdlib.SetSignalAction()` in `Program.Main()` even though it's only a reference to an external method that doesn't necessarily have to be resolved upfront (since we only do the call conditionally). Some indirection might do the trick.

**Comment by alexrp** [comment]
Should be fixed now. Feel free to reopen or file other issues if you still have problems running SDB under .NET.

**Comment by cubrr** [comment]
@alexrp Wow, thanks so much! I had almost given up hope.
