### ISSUE TITLE
Xamarin + sdb samples

### ISSUE THREAD

**Issue by jojojames** [mono/sdb#37]
Would it be possible to show how to debug xamarin apps with sdb?

Noticed this was Xamarin + sdb https://github.com/mono/sdb/issues/8

Building an iOS or Android app should give relevant .exe and .mdb files but I'm not sure how to connect the dots to get it working end to end.

Thanks!

**Comment by alexrp** [comment]
Yes, it is possible. I haven't had the time to document the process properly in SDB's README, but you can follow these instructions (from Xamarin.Android's internal README): https://gist.github.com/alexrp/18de95b295498ccec540a37e69374536

I don't work on Xamarin.iOS, so I am not sure what you would need to do there to get SDB working with it. It should certainly be possible, though - SDB and Xamarin Studio use the same underlying method for connecting.

**Comment by jojojames** [comment]
Thanks! I'll put something here if I find out how to do do it on iOS.
