### ISSUE TITLE
watch command displays duplicate

### ISSUE THREAD

**Issue by callmekohei** [mono/sdb#44]
Hello! I'm `callmekohei`!

# Problems summary
watch command displays duplicate
```
(sdb) watch
#0 's': string it = "aaa"
#0 's': string it = "aaa"
```
like this
![untitled](https://user-images.githubusercontent.com/17691683/34646094-9e7d9150-f3a2-11e7-97be-95436851fff2.gif)

## Expected
watch command display properly.
```
(sdb) watch
#0 's': string it = "aaa"
```
## Environment Information

`sdb vrsion`
```
$ sdb --version
Mono soft debugger (sdb) 1.5.6548.37600
```
`OSX version`
```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88
```

`mono version`
```
$ mono --version
Mono JIT compiler version 5.4.1.6 (tarball Mon Dec 11 14:59:42 GMT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

**Comment by alexrp** [comment]
Looks like I forgot to remove some old code in `WatchCommand.cs` when I made a change quite a while back: https://github.com/mono/sdb/commit/c00902586c9912cebc1fc51d3bf044a985386289#diff-dbc3d896e22389b0f47caa73ac847225

**Comment by callmekohei** [comment]
Oh... ^_^;

**Comment by callmekohei** [comment]
Hello! I'm `callmekohei`!

Thank you!

It's just work well!

like this! (^_^)/

![untitled](https://user-images.githubusercontent.com/17691683/34655216-6e727622-f449-11e7-8f45-3debfc64d9af.gif)
