### ISSUE TITLE
I want to use addCommand (^_^)/

### ISSUE THREAD

**Issue by callmekohei** [mono/sdb#47]
Hello! I'm `callmekohei`!

### Problem

I can not use `addCommand`.

### Expected behavior

I can use `addCommand`

Like this
```fsharp
[<Sealed; Command>]
type MyCommand() =
    inherit Command()
    override __.Names   = [|"mycmd"|]
    override __.Summary = "aaa bbb ccc"
    override __.Syntax  = "ddd eee fff"
    override __.Help    = "Help Help Help"
    override __.Process(args) =

        AddCommand<StepOverCommand>()  // <---- step over

        // run my code after running step over
        Log.Info("hello world")
```

### work around

`(sdb) do , step over , mycmd`

### reason
01. Take time to input when we use sdb on command-line.

02. Flickering screen

like this

![untitled](https://user-images.githubusercontent.com/17691683/34906168-d58f1418-f8aa-11e7-9210-c6fcdc7ccfce.gif)

**Comment by alexrp** [comment]
The correct way to do this is in the constructor, like here for `ThreadCommand` for example: https://github.com/mono/sdb/blob/master/src/Commands/ThreadCommand.cs#L267

**Comment by callmekohei** [comment]
Hello again! I'm `callmekohei`!

So may I have question?

I write code following:

```fsharp
namespace Mono.Debugger.Client.Commands

[<Sealed; Command>]
type MyCommand() =

    inherit MultiCommand()

    override this.Names   = [|"aaaCmd"|]
    override this.Summary = "aaaaaaaaaaa"
    override this.Syntax  = "bbbbbbbbbbb"
    override this.Help    = "ccccccccccc"

    member this.MyCommand() =
        Log.Info("hello world")
```

result
```
(sdb) help

  aaaCmd
    aaaaaaaaaaa

(sdb) help aaaCmd

  bbbbbbbbbbb

ccccccccccc

(sdb) aaaCmd
No 'aaaCmd' sub-command specified
```

Please tell me anything if you have nice idea!

So sorry for `F# code` instead of `C#` code. (^_^;;

**Comment by callmekohei** [comment]
Hello again! I'm `callmekohei`!

So, I can just do it !

Thank you for your advice!

like this
```fsharp
namespace Mono.Debugger.Client.Commands
open Mono.Debugger.Client
open Mono.Debugging.Client

type helloworld() =

    inherit command()

    override __.names   = [|"bbbcmd"|]
    override __.summary = "aaa bbb ccc"
    override __.syntax  = "ddd eee fff"
    override __.help    = "help help help"
    override __.process(args) =
        log.info("hello world from bbbcmd")

[<Sealed; Command>]
type MyCommand() =
    inherit MultiCommand()

    do base.AddCommand<HelloWorld>()

    override this.Names   = [|"aaaCmd"|]
    override this.Summary = "aaaaaaaaaaa"
    override this.Syntax  = "bbbbbbbbbbb"
    override this.Help    = "ccccccccccc"
```
![screen shot 2018-01-14 at 16 07 48](https://user-images.githubusercontent.com/17691683/34913595-1c3efe10-f945-11e7-8afe-18599bb282c5.png)

**Comment by callmekohei** [comment]
And thank you for Japanese F#ers!

https://gitter.im/fsugjp/public?at=5a5a912fba39a53f1a10fd00
